/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tax;

/**
 *
 * @author Mos
 */
public class uitax extends javax.swing.JFrame {

    /**
     * Creates new form uitax
     */
    public uitax() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JPanel();
        dividend = new javax.swing.JSpinner();
        bonus = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        sumIncome = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        salary = new javax.swing.JSpinner();
        salaryYear = new javax.swing.JCheckBox();
        anotherIncome = new javax.swing.JSpinner();
        sumReduce = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        childIn = new javax.swing.JSpinner();
        parent = new javax.swing.JSpinner();
        joint = new javax.swing.JCheckBox();
        out = new javax.swing.JSpinner();
        self = new javax.swing.JSpinner();
        parentMoney = new javax.swing.JSpinner();
        childInMoney = new javax.swing.JSpinner();
        life = new javax.swing.JSpinner();
        health = new javax.swing.JSpinner();
        social = new javax.swing.JSpinner();
        RMF = new javax.swing.JSpinner();
        LTF = new javax.swing.JSpinner();
        travelIn = new javax.swing.JSpinner();
        buyHouse = new javax.swing.JSpinner();
        buyIn = new javax.swing.JSpinner();
        donateEdu = new javax.swing.JSpinner();
        donate = new javax.swing.JSpinner();
        marry = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        donateJing = new javax.swing.JSpinner();
        jLabel47 = new javax.swing.JLabel();
        sumDe = new javax.swing.JSpinner();
        net = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        netSum = new javax.swing.JTextField();
        taxRe = new javax.swing.JTextField();
        taxPlus = new javax.swing.JTextField();
        taxbefore = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        tab1.setBackground(new java.awt.Color(255, 204, 204));

        dividend.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dividendStateChanged(evt);
            }
        });

        bonus.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bonusStateChanged(evt);
            }
        });

        jLabel11.setText("บาท");

        jLabel14.setText("เงินเดือน");

        jLabel15.setText("บาท");

        jLabel16.setText("โบนัส ");

        jLabel17.setText("บาท");

        jLabel18.setText("เงินปันผล");

        jLabel19.setText("บาท");

        jLabel20.setText("รายได้อื่นๆ");

        sumIncome.setText("                      0");
        sumIncome.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                sumIncomeInputMethodTextChanged(evt);
            }
        });
        sumIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumIncomeActionPerformed(evt);
            }
        });

        jLabel21.setText("รวมรายได้");

        jLabel22.setText("บาท");

        salary.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                salaryStateChanged(evt);
            }
        });

        salaryYear.setBackground(new java.awt.Color(255, 204, 204));
        salaryYear.setText("รวมยอดทั้งปี");
        salaryYear.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                salaryYearStateChanged(evt);
            }
        });
        salaryYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryYearActionPerformed(evt);
            }
        });

        anotherIncome.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                anotherIncomeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
            .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tab1Layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab1Layout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addComponent(salaryYear))
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addGap(34, 34, 34)
                    .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab1Layout.createSequentialGroup()
                            .addComponent(bonus, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel15))
                        .addGroup(tab1Layout.createSequentialGroup()
                            .addComponent(dividend, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel17))
                        .addGroup(tab1Layout.createSequentialGroup()
                            .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel11))
                        .addGroup(tab1Layout.createSequentialGroup()
                            .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(anotherIncome)
                                .addComponent(sumIncome))
                            .addGap(18, 18, 18)
                            .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel22))))
                    .addContainerGap(53, Short.MAX_VALUE)))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
            .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tab1Layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(salaryYear)
                        .addComponent(jLabel11))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(bonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(dividend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(anotherIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(sumIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22))
                    .addContainerGap(314, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("เงินได้พึงประเมิน", tab1);

        sumReduce.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("ค่าใช้จ่าย");

        jLabel2.setText("ค่าลดหย่อนส่วนตัว");

        jLabel3.setText("ค่าลดหย่อนคู่สมรส");

        jLabel5.setText("บุตร");

        jLabel7.setText("ลดหย่อนบิดา-มารดา");

        jLabel8.setText("เบี้ยประกันชีวิต");

        jLabel10.setText("เบี้ยประกันสุขภาพบิดา-มารดา");

        jLabel12.setText("เงินสมทบกองทุนประกันสังคม");

        jLabel13.setText("ค่าซื้อหน่วยลงทุนในกองทุนรวมเพื่อการเลี้ยงชีพ");

        jLabel23.setText("ค่าซื้อหน่วยลงทุนในกองทุนรวมหุ้นระยะยาว");

        jLabel24.setText("ดอกเบี้ยเงินกู้ยืมเพื่อซื้อ เช่าซื้อ สร้างที่อยู่อาศัย");

        jLabel25.setText("ค่าเดินทางท่องเที่ยวภายในประเทศ");

        jLabel26.setText("ค่าซื้อสินค้าหรือบริการภายในประเทศ");

        jLabel27.setText("เงินบริจาคสนับสนุนการศึกษา / กีฬา จ่ายจริง");

        jLabel28.setText("เงินบริจาคอื่นๆ");

        jLabel29.setText("รวมค่าใช้จ่าย รายการลดหย่อนและเงินได้ที่ได้รับการยกเว้นภาษี ");

        childIn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                childInStateChanged(evt);
            }
        });

        parent.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                parentStateChanged(evt);
            }
        });

        joint.setText("ยื่นร่วมกัน");
        joint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jointActionPerformed(evt);
            }
        });

        out.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                outStateChanged(evt);
            }
        });

        self.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                selfStateChanged(evt);
            }
        });

        life.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lifeStateChanged(evt);
            }
        });

        health.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                healthStateChanged(evt);
            }
        });

        social.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                socialStateChanged(evt);
            }
        });

        RMF.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RMFStateChanged(evt);
            }
        });

        LTF.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                LTFStateChanged(evt);
            }
        });

        travelIn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                travelInStateChanged(evt);
            }
        });

        buyHouse.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buyHouseStateChanged(evt);
            }
        });

        buyIn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buyInStateChanged(evt);
            }
        });

        donateEdu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                donateEduStateChanged(evt);
            }
        });

        donate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                donateStateChanged(evt);
            }
        });

        jLabel30.setText("บาท");

        jLabel31.setText("บาท");

        jLabel32.setText("บาท");

        jLabel33.setText("บาท");

        jLabel34.setText("บาท");

        jLabel35.setText("บาท");

        jLabel36.setText("บาท");

        jLabel37.setText("บาท");

        jLabel38.setText("บาท");

        jLabel39.setText("บาท");

        jLabel40.setText("บาท");

        jLabel41.setText("บาท");

        jLabel43.setText("บาท");

        jLabel44.setText("บาท");

        jLabel45.setText("บาท");

        jLabel46.setText("บาท");

        jLabel42.setText("ที่ลดหย่อนได้(2เท่าแต่ไม่เกิน 10%หลังหักค่าใช้จ่าย)");

        donateJing.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                donateJingStateChanged(evt);
            }
        });

        jLabel47.setText("บาท");

        sumDe.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sumDeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout sumReduceLayout = new javax.swing.GroupLayout(sumReduce);
        sumReduce.setLayout(sumReduceLayout);
        sumReduceLayout.setHorizontalGroup(
            sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sumReduceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(sumReduceLayout.createSequentialGroup()
                        .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addGroup(sumReduceLayout.createSequentialGroup()
                                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel23)
                                    .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sumReduceLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(joint))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sumReduceLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(sumReduceLayout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(childIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel27))
                                .addGap(95, 95, 95)
                                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(life)
                                    .addComponent(RMF)
                                    .addComponent(LTF)
                                    .addComponent(travelIn)
                                    .addComponent(buyHouse)
                                    .addComponent(buyIn)
                                    .addComponent(social)
                                    .addComponent(health)
                                    .addComponent(childInMoney)
                                    .addComponent(parentMoney)
                                    .addComponent(out)
                                    .addComponent(self)
                                    .addComponent(marry)
                                    .addComponent(donateEdu, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(sumReduceLayout.createSequentialGroup()
                                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29))
                                .addGap(23, 23, 23)
                                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(donate)
                                    .addComponent(sumDe))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel41)
                            .addComponent(jLabel38)
                            .addComponent(jLabel37)
                            .addComponent(jLabel36)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel31)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44)
                            .addComponent(jLabel46)
                            .addComponent(jLabel45)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sumReduceLayout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(donateJing, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sumReduceLayout.setVerticalGroup(
            sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sumReduceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel46)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(self, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addGap(18, 18, 18)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(joint))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(marry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel43)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(childIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(childInMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel44)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parentMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(life, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(health, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel33)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(social, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RMF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel34)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(travelIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel36)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buyHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buyIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(donateEdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(18, 18, 18)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(donateJing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(donate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sumReduceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel41)
                    .addComponent(sumDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("ค่าใช้จ่าย ค่าลดหย่อน", sumReduce);

        net.setBackground(new java.awt.Color(0, 204, 204));

        jLabel4.setText("ภาษีหัก ณ ที่จ่าย");

        jLabel6.setText("รายได้พึงประเมิน สำหรับคำนวนภาษี");

        jLabel9.setText("ภาษีที่ท่านสามารถขอคืน");

        jLabel48.setText("ภาษีที่ท่านต้องจ่ายเพิ่ม");

        netSum.setText("               0");
        netSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netSumActionPerformed(evt);
            }
        });

        taxRe.setText("               0");

        taxPlus.setText("               0");

        javax.swing.GroupLayout netLayout = new javax.swing.GroupLayout(net);
        net.setLayout(netLayout);
        netLayout.setHorizontalGroup(
            netLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(netLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(netLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(netLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(taxRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(netLayout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(taxPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, netLayout.createSequentialGroup()
                        .addGroup(netLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, netLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18))
                            .addGroup(netLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(105, 105, 105)))
                        .addGroup(netLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(taxbefore)
                            .addComponent(netSum))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        netLayout.setVerticalGroup(
            netLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(netLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(netLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(netSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(netLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(taxbefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(netLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(taxRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(netLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(taxPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(365, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("ภาษีที่ต้องชำระ", net);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dividendStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dividendStateChanged
        // TODO add your handling code here:
        int sumSalary =0;
        if(salaryYear.isSelected())
        {
           sumSalary = (Integer) salary.getValue();
        }
        else
        {
           sumSalary = ((Integer) salary.getValue())*12;
        }
        int sumBonus = (Integer) bonus.getValue();
        int sumDividend = (Integer) dividend.getValue();
        int sumAnotherIncome = (Integer) anotherIncome.getValue();
        int SUMIncome = sumSalary + sumBonus + sumDividend + sumAnotherIncome;
        sumIncome.setText (String.valueOf(SUMIncome));
    }//GEN-LAST:event_dividendStateChanged

    private void bonusStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bonusStateChanged
        // TODO add your handling code here:
        int sumSalary =0;
        if(salaryYear.isSelected())
        {
           sumSalary = (Integer) salary.getValue();
        }
        else
        {
           sumSalary = ((Integer) salary.getValue())*12;
        }
        int sumBonus = (Integer) bonus.getValue();
        int sumDividend = (Integer) dividend.getValue();
        int sumAnotherIncome = (Integer) anotherIncome.getValue();
        int SUMIncome = sumSalary + sumBonus + sumDividend + sumAnotherIncome;
        sumIncome.setText (String.valueOf(SUMIncome));
    }//GEN-LAST:event_bonusStateChanged

    private void sumIncomeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_sumIncomeInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_sumIncomeInputMethodTextChanged

    private void sumIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumIncomeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sumIncomeActionPerformed

    private void salaryStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_salaryStateChanged
        // TODO add your handling code here:
        int sumSalary =0;
        if(salaryYear.isSelected())
        {
           sumSalary = (Integer) salary.getValue();
        }
        else
        {
           sumSalary = ((Integer) salary.getValue())*12;
        }
        int sumBonus = (Integer) bonus.getValue();
        int sumDividend = (Integer) dividend.getValue();
        int sumAnotherIncome = (Integer) anotherIncome.getValue();
        int SUMIncome = sumSalary + sumBonus + sumDividend + sumAnotherIncome;
        sumIncome.setText (String.valueOf(SUMIncome));
    }//GEN-LAST:event_salaryStateChanged

    private void salaryYearStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_salaryYearStateChanged
        // TODO add your handling code here:
        int sumSalary =0;
        if(salaryYear.isSelected())
        {
           sumSalary = (Integer) salary.getValue();
        }
        else
        {
           sumSalary = ((Integer) salary.getValue())*12;
        }
        int sumBonus = (Integer) bonus.getValue();
        int sumDividend = (Integer) dividend.getValue();
        int sumAnotherIncome = (Integer) anotherIncome.getValue();
        int SUMIncome = sumSalary + sumBonus + sumDividend + sumAnotherIncome;
        sumIncome.setText (String.valueOf(SUMIncome));
    }//GEN-LAST:event_salaryYearStateChanged

    private void salaryYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryYearActionPerformed

    private void anotherIncomeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_anotherIncomeStateChanged
        // TODO add your handling code here:
        int sumSalary =0;
        if(salaryYear.isSelected())
        {
           sumSalary = (Integer) salary.getValue();
        }
        else
        {
           sumSalary = ((Integer) salary.getValue())*12;
        }
        int sumBonus = (Integer) bonus.getValue();
        int sumDividend = (Integer) dividend.getValue();
        int sumAnotherIncome = (Integer) anotherIncome.getValue();
        int SUMIncome = sumSalary + sumBonus + sumDividend + sumAnotherIncome;
        sumIncome.setText (String.valueOf(SUMIncome));
    }//GEN-LAST:event_anotherIncomeStateChanged

    private void jointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jointActionPerformed
        // TODO add your handling code here:
        if(joint.isSelected())
        {
            marry.setValue(60000);
        }
        else
        {
            marry.setValue(0);
        }
    }//GEN-LAST:event_jointActionPerformed

    private void outStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_outStateChanged
        // TODO add your handling code here:
        int SUMIncome = Integer.parseInt(sumIncome.getText());
        int OUT = (Integer) out.getValue();
        if(OUT >= SUMIncome/2)
        {
            OUT = SUMIncome/2;
        }
        
        if(OUT >= 100000)
        {
            OUT = 100000;
        }
        
        out.setValue(OUT);
    }//GEN-LAST:event_outStateChanged

    private void selfStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_selfStateChanged
        // TODO add your handling code here:
        self.setValue(60000);
    }//GEN-LAST:event_selfStateChanged

    private void childInStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_childInStateChanged
        // TODO add your handling code here:
        int baby = (Integer) childIn.getValue();
        if(baby >3)
        {
            childInMoney.setValue(90000);
        }
        else
        {
            childInMoney.setValue(30000*baby);
        }
    }//GEN-LAST:event_childInStateChanged

    private void parentStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_parentStateChanged
        // TODO add your handling code here:
        int MAMA = (Integer) parent.getValue();
        if(MAMA>3)
        {
            parentMoney.setValue(90000);
        }
        else
        {
            parentMoney.setValue(30000*MAMA);
        }
    }//GEN-LAST:event_parentStateChanged

    private void lifeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lifeStateChanged
        // TODO add your handling code here:
        int pragan = (Integer) life.getValue();
        if(pragan >100000)
        {
            life.setValue(100000);
        }
       
    }//GEN-LAST:event_lifeStateChanged

    private void healthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_healthStateChanged
        // TODO add your handling code here:
        int pragan = (Integer) health.getValue();
        if(pragan >15000)
        {
            health.setValue(15000);
        }
    }//GEN-LAST:event_healthStateChanged

    private void socialStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_socialStateChanged
        // TODO add your handling code here:
        int pragan = (Integer) social.getValue();
        if(pragan >9000)
        {
            social.setValue(9000);
        }
    }//GEN-LAST:event_socialStateChanged

    private void RMFStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RMFStateChanged
        // TODO add your handling code here:
        int SUMIncome = Integer.parseInt(sumIncome.getText());
        int rmff = (Integer) RMF.getValue();
        if(rmff >= SUMIncome/6)
        {
            rmff = SUMIncome/6;
        }
        
        if(rmff >= 500000)
        {
            rmff = 500000;
        }
        
        RMF.setValue(rmff);
    }//GEN-LAST:event_RMFStateChanged

    private void LTFStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_LTFStateChanged
        // TODO add your handling code here:
        int SUMIncome = Integer.parseInt(sumIncome.getText());
        int ltff = (Integer) LTF.getValue();
        if(ltff >= SUMIncome/6)
        {
            ltff = SUMIncome/6;
        }
        
        if(ltff >= 500000)
        {
            ltff = 500000;
        }
        
        LTF.setValue(ltff);
    }//GEN-LAST:event_LTFStateChanged

    private void travelInStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_travelInStateChanged
        // TODO add your handling code here:
        int Tra = (Integer) travelIn.getValue();
        if(Tra >15000)
        {
            travelIn.setValue(15000);
        }
              
    }//GEN-LAST:event_travelInStateChanged

    private void buyHouseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buyHouseStateChanged
        // TODO add your handling code here:
        int home = (Integer) buyHouse.getValue();
        if(home >100000)
        {
            buyHouse.setValue(100000);
        }
       
    }//GEN-LAST:event_buyHouseStateChanged

    private void buyInStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buyInStateChanged
        // TODO add your handling code here:
        int product = (Integer) buyIn.getValue();
        if(product >15000)
        {
            buyIn.setValue(15000);
        }
    }//GEN-LAST:event_buyInStateChanged

    private void donateEduStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_donateEduStateChanged
        // TODO add your handling code here:
        int SUMIncome = Integer.parseInt(sumIncome.getText());
        int a= (Integer)out.getValue();
        int b =(Integer)self.getValue();
        int c = (Integer)marry.getValue();
        int d =(Integer)childInMoney.getValue();
        int e = (Integer)parentMoney.getValue();
        int f=(Integer)life.getValue();
        int g =(Integer)health.getValue();
        int h =(Integer)social.getValue();
        int i =(Integer)RMF.getValue();
        int j =(Integer)LTF.getValue();
        int k =(Integer)travelIn.getValue();
        int l = (Integer)buyHouse.getValue();
        int m = (Integer)buyIn.getValue(); 
        int SUMReduce = a+b+c+d+e+f+g+h+i+j+k+l+m;
        
        int edu = (Integer)donateEdu.getValue();
        int don = (SUMIncome-SUMReduce)/10;
        if((edu*2)>don)
        {
            donateJing.setValue(don);
        }
        else
        {
            donateJing.setValue(edu*2);
        }

 
    }//GEN-LAST:event_donateEduStateChanged

    private void donateJingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_donateJingStateChanged
        // TODO add your handling code here:
        int SUMIncome = Integer.parseInt(sumIncome.getText());
        int a= (Integer)out.getValue();
        int b =(Integer)self.getValue();
        int c = (Integer)marry.getValue();
        int d =(Integer)childInMoney.getValue();
        int e = (Integer)parentMoney.getValue();
        int f=(Integer)life.getValue();
        int g =(Integer)health.getValue();
        int h =(Integer)social.getValue();
        int i =(Integer)RMF.getValue();
        int j =(Integer)LTF.getValue();
        int k =(Integer)travelIn.getValue();
        int l = (Integer)buyHouse.getValue();
        int m = (Integer)buyIn.getValue(); 
        int SUMReduce = a+b+c+d+e+f+g+h+i+j+k+l+m;
        
        int edu = (Integer)donateEdu.getValue();
        int don = (SUMIncome-SUMReduce)/10;
        if((edu*2)>don)
        {
            donateJing.setValue(don);
        }
        else
        {
            donateJing.setValue(edu*2);
        }
    }//GEN-LAST:event_donateJingStateChanged

    private void donateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_donateStateChanged
        // TODO add your handling code here:
        int SUMIncome = Integer.parseInt(sumIncome.getText());
        int a= (Integer)out.getValue();
        int b =(Integer)self.getValue();
        int c = (Integer)marry.getValue();
        int d =(Integer)childInMoney.getValue();
        int e = (Integer)parentMoney.getValue();
        int f=(Integer)life.getValue();
        int g =(Integer)health.getValue();
        int h =(Integer)social.getValue();
        int i =(Integer)RMF.getValue();
        int j =(Integer)LTF.getValue();
        int k =(Integer)travelIn.getValue();
        int l = (Integer)buyHouse.getValue();
        int m = (Integer)buyIn.getValue(); 
        int n = (Integer)donateJing.getValue(); 
        int SUMReduce = a+b+c+d+e+f+g+h+i+j+k+l+m+n;
        
        int DONATE = (Integer)donate.getValue();
        int don = (SUMIncome-SUMReduce)/10;
        if(DONATE>don)
        {
            donate.setValue(don);
        }
        else
        {
            donate.setValue(DONATE);
        }
    }//GEN-LAST:event_donateStateChanged

    private void sumDeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sumDeStateChanged
        // TODO add your handling code here:
        int SUMIncome = Integer.parseInt(sumIncome.getText());
        int a= (Integer)out.getValue();
        int b =(Integer)self.getValue();
        int c = (Integer)marry.getValue();
        int d =(Integer)childInMoney.getValue();
        int e = (Integer)parentMoney.getValue();
        int f=(Integer)life.getValue();
        int g =(Integer)health.getValue();
        int h =(Integer)social.getValue();
        int i =(Integer)RMF.getValue();
        int j =(Integer)LTF.getValue();
        int k =(Integer)travelIn.getValue();
        int l = (Integer)buyHouse.getValue();
        int m = (Integer)buyIn.getValue(); 
        int n = (Integer)donateJing.getValue();
        int o = (Integer)donate.getValue();
        int SUMReduce = a+b+c+d+e+f+g+h+i+j+k+l+m+n+o;
        
        //int netIncome = SUMIncome-SUMReduce;
        sumDe.setValue(SUMReduce);
        
     
        
    }//GEN-LAST:event_sumDeStateChanged

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        // TODO add your handling code here:
        int SUMIncome = Integer.parseInt(sumIncome.getText());
        int a= (Integer)out.getValue();
        int b =(Integer)self.getValue();
        int c = (Integer)marry.getValue();
        int d =(Integer)childInMoney.getValue();
        int e = (Integer)parentMoney.getValue();
        int f=(Integer)life.getValue();
        int g =(Integer)health.getValue();
        int h =(Integer)social.getValue();
        int i =(Integer)RMF.getValue();
        int j =(Integer)LTF.getValue();
        int k =(Integer)travelIn.getValue();
        int l = (Integer)buyHouse.getValue();
        int m = (Integer)buyIn.getValue(); 
        int n = (Integer)donateJing.getValue();
        int o = (Integer)donate.getValue();
        int SUMReduce = a+b+c+d+e+f+g+h+i+j+k+l+m+n+o;
        
        int netIncome = SUMIncome-SUMReduce;
        netSum.setText (String.valueOf(netIncome));
        
        int tang = netIncome;
        double tax = 0.0;
        double taxcal = 0.0;
        if (tang > 5000000)
        {
        //35%
        taxcal = (tang-5000000)*0.35;
        tax = tax + taxcal;
        tang = 5000000;
            
        }
        if (tang > 2000000)
        {
            //30%
            taxcal = (tang-2000000)*0.3;
            tax = tax + taxcal;
            tang = 2000000;

        }
        if (tang > 1000000)
        {
            //25%
             taxcal = (tang-1000000)*0.25;
             tax = tax + taxcal;
             tang = 1000000;

        }
        if (tang > 750000)
        {
            //20%
            taxcal = (tang-750000)*0.2;
            tax = tax + taxcal;
            tang = 750000;

        }
        if (tang > 500000)
        {
            //15%
            taxcal = (tang-500000)*0.15;
            tax = tax + taxcal;
            tang = 500000;
              
        }
        if (tang > 300000)
        {
            //10%
            taxcal = (tang-300000)*0.1;
            tax = tax + taxcal;
            tang = 300000;

        }
         if (tang > 150000)
        {
             //5%
            taxcal = (tang-150000)*0.05;
            tax = tax + taxcal;
            tang = 150000;

        }
          
        int TBF=(Integer)taxbefore.getValue();
        double finaltax = tax-TBF;
        if (finaltax >=0)
        {
            taxPlus.setText (String.valueOf(finaltax));
        }
        else if (finaltax <0)
        {
            taxRe.setText (String.valueOf(Math.abs(finaltax)));
        }
        
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void netSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netSumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netSumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uitax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uitax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uitax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uitax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uitax().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner LTF;
    private javax.swing.JSpinner RMF;
    private javax.swing.JSpinner anotherIncome;
    private javax.swing.JSpinner bonus;
    private javax.swing.JSpinner buyHouse;
    private javax.swing.JSpinner buyIn;
    private javax.swing.JSpinner childIn;
    private javax.swing.JSpinner childInMoney;
    private javax.swing.JSpinner dividend;
    private javax.swing.JSpinner donate;
    private javax.swing.JSpinner donateEdu;
    private javax.swing.JSpinner donateJing;
    private javax.swing.JSpinner health;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JCheckBox joint;
    private javax.swing.JSpinner life;
    private javax.swing.JSpinner marry;
    private javax.swing.JPanel net;
    private javax.swing.JTextField netSum;
    private javax.swing.JSpinner out;
    private javax.swing.JSpinner parent;
    private javax.swing.JSpinner parentMoney;
    private javax.swing.JSpinner salary;
    private javax.swing.JCheckBox salaryYear;
    private javax.swing.JSpinner self;
    private javax.swing.JSpinner social;
    private javax.swing.JSpinner sumDe;
    private javax.swing.JTextField sumIncome;
    private javax.swing.JPanel sumReduce;
    private javax.swing.JPanel tab1;
    private javax.swing.JTextField taxPlus;
    private javax.swing.JTextField taxRe;
    private javax.swing.JSpinner taxbefore;
    private javax.swing.JSpinner travelIn;
    // End of variables declaration//GEN-END:variables
}
